name: Azure Container Registry + Azure Kubernetes Service

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login no Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build e Push no Azure Container Registry
      run: |
        cd ${{ secrets.PATH_PROJETO }}
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}:latest
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}

    - name: Azure Kubernetes Service - set context - Conectando ao cluster
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP_K8S }}
        cluster-name:  ${{ secrets.AZURE_CLUSTER_K8S }}

    - name: Azure Kubernetes Service - Criando Secret para acesso ao Container Registry
      uses: Azure/k8s-create-secret@v1
      with:
        namespace: ${{ secrets.NAMESPACE_K8S }}
        container-registry-url: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
        container-registry-username: ${{ secrets.DOCKER_USERNAME }}
        container-registry-password: ${{ secrets.DOCKER_PASSWORD }}
        secret-name: webapp-k8s-secret

    - name: kubectl - Exibindo a versão
      run: kubectl version

    - name: kubectl - Removendo o Deployment caso exista
      run: kubectl delete deployment --ignore-not-found ${{ secrets.DEPLOYMENT_K8S }} -n ${{ secrets.NAMESPACE_K8S }}

    - name: Azure Kubernetes Service - Deployment de Web App
      uses: Azure/k8s-deploy@v1
      with:
        namespace: ${{ secrets.NAMESPACE_K8S }}
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/${{ secrets.NOME_IMAGEM }}:latest
        imagepullsecrets: |
          webapp-k8s-secret